#!/usr/bin/env python3
"""
Curated AiMY catalogue.

This is the SINGLE source of customer-facing truth. The refresh pipeline
publishes ONLY the features defined here. Everything else in Jira is routed to
the private evidence file or the review-needed queue — never published raw.

Each entry is written in customer-safe marketing language and carries an
`epic_match` list of case-insensitive substrings. The pipeline scans the live
Jira cache for issues whose summary contains any of those substrings, binds the
matching issue keys as private evidence, and resolves the display date from that
evidence (fixVersion release date -> resolution date -> last updated).

To add a feature: copy a block, write customer-safe copy, and point `epic_match`
at one or more real Jira epic/story titles. Never put a Jira key in any public
field. `id` is a stable slug and must never change once published.

Allowed module values (must match OUTPUT_SCHEMA module ids in refresh-catalogue.py):
  AiMY Knowledge | AiMY Voice | AiMY QA | AiMY Connect |
  AiMY Sales — BDR Mode | AiMY Sales — Manager Mode |
  Continuous Improvement Loop | Platform / Integrations

Allowed availability values:
  Released | Recently Updated | Coming Soon | Needs Review
"""

# Module display name -> module id used by the website renderer / OUTPUT_SCHEMA.
MODULE_IDS = {
    "AiMY Knowledge": "knowledge",
    "AiMY Voice": "voice",
    "AiMY QA": "qa",
    "AiMY Connect": "connect",
    "AiMY Sales — BDR Mode": "sales-bdr",
    "AiMY Sales — Manager Mode": "sales-manager",
    "Continuous Improvement Loop": "loop",
    "Platform / Integrations": "knowledge",
}

CURATED_FEATURES = [
    # ─────────────────────────── AiMY Knowledge ───────────────────────────
    {
        "id": "knowledge-multi-source-ingestion",
        "track": "support",
        "module": "AiMY Knowledge",
        "featureName": "Multi-Source Knowledge Ingestion",
        "shortDescription": "Securely connects to your existing help content — SOPs, manuals, FAQs, and playbooks — and turns it into one verified, searchable knowledge layer.",
        "customerProblem": "Knowledge is scattered across drives, wikis, chat threads, and senior agents' heads, so answers are inconsistent and slow.",
        "customerValue": "A single source of truth that both support agents and sales reps can trust from day one.",
        "whatChanged": "Released the ingestion and indexing layer that grounds every AiMY answer in your real, approved content.",
        "availability": "Released",
        "bestFor": ["Support Leaders", "Agents"],
        "tags": ["knowledge", "single-source-of-truth", "onboarding"],
        "epic_match": ["aimy k [dynamic agent]", "aimy k: analysis service", "aimy k n] apply the new design"],
    },
    {
        "id": "knowledge-grounded-answer-console",
        "track": "support",
        "module": "AiMY Knowledge",
        "featureName": "Grounded Answer Console",
        "shortDescription": "A natural-language console that gives agents and reps fast, contextual answers drawn only from your verified knowledge.",
        "customerProblem": "Agents lose time hunting for the right policy or answer and often guess, creating inconsistent customer conversations.",
        "customerValue": "Faster handle times and consistent answers, regardless of who is on shift.",
        "whatChanged": "Released the conversational answer experience built on the verified knowledge layer.",
        "availability": "Released",
        "bestFor": ["Agents", "Support Leaders"],
        "tags": ["knowledge", "agent-assist", "consistency"],
        "epic_match": ["aimy k ] ui/ux enhancements", "aimy k n] main page", "aimy k n] agent details"],
    },
    {
        "id": "knowledge-user-management",
        "track": "support",
        "module": "AiMY Knowledge",
        "featureName": "Roles & Access Management",
        "shortDescription": "Controls who can see and manage knowledge, entities, and permissions across teams.",
        "customerProblem": "Without clear access controls, sensitive content and admin settings are hard to govern as teams grow.",
        "customerValue": "Confident, governed rollout across departments without exposing the wrong content to the wrong people.",
        "whatChanged": "Released user, role, and permission management for the knowledge platform.",
        "availability": "Released",
        "bestFor": ["Support Leaders"],
        "tags": ["knowledge", "governance", "access-control"],
        "epic_match": ["[aimy k] user management", "user management"],
    },
    {
        "id": "knowledge-contactable-hyperlinks",
        "track": "support",
        "module": "AiMY Knowledge",
        "featureName": "Actionable Answer Links",
        "shortDescription": "Answers can include live, clickable links and contactable actions so agents move from answer to action in one step.",
        "customerProblem": "Static answers still leave agents copying references and switching tabs to act on them.",
        "customerValue": "Less context-switching and faster resolution from a single answer surface.",
        "whatChanged": "Released contactable hyperlinks across the platform.",
        "availability": "Released",
        "bestFor": ["Agents"],
        "tags": ["knowledge", "productivity"],
        "epic_match": ["contactable hyperlinks across platform"],
    },

    # ──────────────────────────── AiMY Voice ──────────────────────────────
    {
        "id": "voice-calls-integration",
        "track": "support",
        "module": "AiMY Voice",
        "featureName": "Integrated Voice Channel",
        "shortDescription": "Brings phone calls into the same intelligence layer as chat and tickets, so voice stops being a black box.",
        "customerProblem": "Voice conversations are hard to monitor, search, and feed back into improvement, even though they hold the richest signals.",
        "customerValue": "Calls become searchable, coachable operational data instead of disappearing after they end.",
        "whatChanged": "Released the calls integration that connects voice interactions to AiMY.",
        "availability": "Released",
        "bestFor": ["Support Leaders", "Supervisors"],
        "tags": ["voice", "channel-coverage"],
        "epic_match": ["integrate aimy calls", "aimy calls integration"],
    },
    {
        "id": "voice-twilio-infrastructure",
        "track": "support",
        "module": "AiMY Voice",
        "featureName": "Native Calling Infrastructure",
        "shortDescription": "Enterprise-grade inbound and outbound calling built natively into AiMY.",
        "customerProblem": "Stitching telephony to support tooling is fragile and leaves gaps in coverage.",
        "customerValue": "A reliable voice foundation that the rest of the improvement loop can build on.",
        "whatChanged": "Building native voice infrastructure for inbound and outbound calls.",
        "availability": "Coming Soon",
        "bestFor": ["Support Leaders"],
        "tags": ["voice", "infrastructure", "roadmap"],
        "epic_match": ["twilio voice infrastructure"],
    },
    {
        "id": "voice-active-call-screen",
        "track": "support",
        "module": "AiMY Voice",
        "featureName": "Active Call Assist Screen",
        "shortDescription": "A live call screen that shows transcription and matching knowledge side-by-side while an agent is on a call.",
        "customerProblem": "Agents handle calls without real-time support, so quality depends on memory and tenure.",
        "customerValue": "Real-time guidance that lifts first-call resolution and consistency.",
        "whatChanged": "Designing the active call experience with live assist.",
        "availability": "Coming Soon",
        "bestFor": ["Agents", "Supervisors"],
        "tags": ["voice", "agent-assist", "roadmap"],
        "epic_match": ["active call screen", "incoming call experience"],
    },
    {
        "id": "voice-post-call-intelligence",
        "track": "support",
        "module": "AiMY Voice",
        "featureName": "Post-Call Intelligence",
        "shortDescription": "Turns finished calls into structured summaries, outcomes, and follow-up actions automatically.",
        "customerProblem": "After a call ends, its value is usually lost to manual notes or nothing at all.",
        "customerValue": "Every call feeds QA, knowledge, and follow-up without manual write-up.",
        "whatChanged": "Building post-call summarisation and follow-up actions.",
        "availability": "Coming Soon",
        "bestFor": ["Supervisors", "Support Leaders"],
        "tags": ["voice", "automation", "roadmap"],
        "epic_match": ["post-call intelligence"],
    },

    # ───────────────────────────── AiMY QA ────────────────────────────────
    {
        "id": "qa-v1-core",
        "track": "support",
        "module": "AiMY QA",
        "featureName": "Continuous Conversation QA",
        "shortDescription": "Evaluates support interactions against your quality standards instead of reviewing a small manual sample.",
        "customerProblem": "Manual QA reviews a fraction of conversations, catches issues late, and misses recurring patterns.",
        "customerValue": "Quality becomes a live signal with far broader coverage than manual sampling.",
        "whatChanged": "Released the QA v1 evaluation platform.",
        "availability": "Released",
        "bestFor": ["Support Leaders", "Supervisors"],
        "tags": ["qa", "coverage", "quality"],
        "epic_match": ["aimy qa v1", "[aimy qa v1] admin", "[aimy qa v1] calls", "[aimy qa v1] client requirement"],
    },
    {
        "id": "qa-bulk-call-uploads",
        "track": "support",
        "module": "AiMY QA",
        "featureName": "Bulk Call Review at Scale",
        "shortDescription": "Upload and evaluate large volumes of calls at once so historical and high-volume operations are fully covered.",
        "customerProblem": "High call volumes make it impossible to review conversations one at a time.",
        "customerValue": "QA keeps pace with real operational volume instead of falling behind.",
        "whatChanged": "Released bulk call uploads and large-call handling.",
        "availability": "Released",
        "bestFor": ["Support Leaders", "Supervisors"],
        "tags": ["qa", "scale", "voice"],
        "epic_match": ["enable bulk call uploads", "enhance large call handling"],
    },
    {
        "id": "qa-insights-charts",
        "track": "support",
        "module": "AiMY QA",
        "featureName": "Insights & Trend Charts",
        "shortDescription": "Turns QA results into clear charts and conversational insights so leaders can see patterns, not just scores.",
        "customerProblem": "Raw QA scores are hard to act on without seeing trends and drivers.",
        "customerValue": "Leaders spot recurring issues and coaching opportunities at a glance.",
        "whatChanged": "Released insight enhancements and charts inside the insights chat.",
        "availability": "Released",
        "bestFor": ["Support Leaders", "Supervisors"],
        "tags": ["qa", "insights", "reporting"],
        "epic_match": ["insight enhancement", "integrate charts into insights chat"],
    },
    {
        "id": "qa-dispute-management",
        "track": "support",
        "module": "AiMY QA",
        "featureName": "QA Dispute Management",
        "shortDescription": "A structured workflow for agents to dispute QA outcomes and for leads to resolve them fairly.",
        "customerProblem": "Automated scoring without a review path erodes agent trust and adoption.",
        "customerValue": "Fair, transparent QA that teams actually trust and adopt.",
        "whatChanged": "Released the QA dispute system.",
        "availability": "Released",
        "bestFor": ["Supervisors", "Agents"],
        "tags": ["qa", "fairness", "adoption"],
        "epic_match": ["dispute system", "dispute management"],
    },
    {
        "id": "qa-evaluation-engine-v2",
        "track": "support",
        "module": "AiMY QA",
        "featureName": "AI Evaluation Engine",
        "shortDescription": "Next-generation evaluation that scores tone, accuracy, and compliance across every interaction.",
        "customerProblem": "Consistent, compliance-aware scoring is hard to achieve manually at scale.",
        "customerValue": "Critical risks and tone issues are flagged within minutes of a conversation closing.",
        "whatChanged": "Building the v2 AI evaluation engine.",
        "availability": "Coming Soon",
        "bestFor": ["Support Leaders", "Supervisors"],
        "tags": ["qa", "compliance", "roadmap"],
        "epic_match": ["ai evaluation engine", "ai interaction evaluation"],
    },

    # ─────────────────────────── AiMY Connect ─────────────────────────────
    {
        "id": "connect-urgency-escalation",
        "track": "support",
        "module": "AiMY Connect",
        "featureName": "Proactive Urgency & Escalation Detection",
        "shortDescription": "Identifies urgent and at-risk interactions and alerts supervisors before they escalate.",
        "customerProblem": "Supervisors often discover problems only after escalation, SLA risk, or quality drift has already happened.",
        "customerValue": "Supervisors move from firefighting to acting early on the cases that matter most.",
        "whatChanged": "Released the urgency and escalation engine with AI alerts on interactions.",
        "availability": "Released",
        "bestFor": ["Supervisors", "Support Leaders"],
        "tags": ["connect", "escalation", "real-time"],
        "epic_match": ["urgency & escalation", "ai alerts to the interactions", "critical support escalation"],
    },
    {
        "id": "connect-operations-hub",
        "track": "support",
        "module": "AiMY Connect",
        "featureName": "Supervisor Operations Hub",
        "shortDescription": "A real-time operating view of queue pressure, agent state, and risk for supervisors, stakeholders, and clients.",
        "customerProblem": "Supervisors lack a single live picture of floor operations and have to chase status manually.",
        "customerValue": "A clear operating picture that supports proactive, evidence-based decisions.",
        "whatChanged": "Building the Operations Hub visibility dashboard.",
        "availability": "Recently Updated",
        "bestFor": ["Supervisors", "Support Leaders"],
        "tags": ["connect", "visibility", "operations"],
        "epic_match": ["operations hub", "operational risk dashboard"],
    },
    {
        "id": "connect-sla-routing",
        "track": "support",
        "module": "AiMY Connect",
        "featureName": "SLA-Aware Triage & Routing",
        "shortDescription": "Prioritises and routes work based on SLA risk, customer tier, and sentiment.",
        "customerProblem": "Without smart routing, high-value and at-risk customers wait in the same queue as everyone else.",
        "customerValue": "Protects key accounts by getting the right cases to the right people first.",
        "whatChanged": "Building SLA-aware triage, routing, and proactive breach alerting.",
        "availability": "Coming Soon",
        "bestFor": ["Supervisors", "Support Leaders"],
        "tags": ["connect", "routing", "roadmap"],
        "epic_match": ["sla-aware routing", "ticket triage", "sla breach detection", "queue management"],
    },

    # ─────────────────────── AiMY Sales — BDR Mode ────────────────────────
    {
        "id": "sales-bdr-knowledge",
        "track": "sales",
        "module": "AiMY Sales — BDR Mode",
        "featureName": "Sales Playbooks & Collateral Layer",
        "shortDescription": "Gives reps one grounded place for approved messaging, positioning, battlecards, and collateral.",
        "customerProblem": "Product knowledge and proof points are scattered, so every rep runs a slightly different motion.",
        "customerValue": "Every rep works from the same approved playbooks and positioning.",
        "whatChanged": "Released the sales knowledge experience.",
        "availability": "Released",
        "bestFor": ["BDRs", "Sales Leaders"],
        "tags": ["sales", "playbooks", "consistency"],
        "epic_match": ["aimy sales"],
    },
    {
        "id": "sales-bdr-outbound-dispatch",
        "track": "sales",
        "module": "AiMY Sales — BDR Mode",
        "featureName": "Playbook-Grounded Outreach",
        "shortDescription": "Helps BDRs draft, sequence, and follow up using approved messaging and account context.",
        "customerProblem": "Outreach varies by rep, creating inconsistent messaging and follow-up cadence.",
        "customerValue": "A repeatable outbound motion that helps new reps ramp faster.",
        "whatChanged": "Building BDR outbound dispatch and follow-up sequencing.",
        "availability": "Coming Soon",
        "bestFor": ["BDRs", "Sales Managers"],
        "tags": ["sales", "outreach", "roadmap"],
        "epic_match": ["outbound bdr dispatch", "bdr dispatch"],
    },

    # ───────────────────── AiMY Sales — Manager Mode ──────────────────────
    {
        "id": "sales-manager-pipeline-visibility",
        "track": "sales",
        "module": "AiMY Sales — Manager Mode",
        "featureName": "Natural-Language Pipeline Visibility for Managers",
        "shortDescription": "Sales managers can ask natural-language questions about pipeline movement, stalled deals, recent activity, and coaching opportunities.",
        "customerProblem": "Managers rely on stale CRM updates, gut-feel forecasting, and manual rep check-ins.",
        "customerValue": "Managers get a clearer operating picture without chasing reps for manual updates.",
        "whatChanged": "Building queryable, natural-language pipeline visibility.",
        "availability": "Coming Soon",
        "bestFor": ["Sales Managers", "Sales Leaders"],
        "tags": ["sales", "pipeline", "roadmap"],
        "epic_match": ["sales supervisor operations hub", "pipeline"],
    },
    {
        "id": "sales-manager-bdr-activity",
        "track": "sales",
        "module": "AiMY Sales — Manager Mode",
        "featureName": "BDR Activity & Coverage Console",
        "shortDescription": "Tracks outbound activity, lead queue health, and coverage so managers can rebalance on the fly.",
        "customerProblem": "Managers can't easily see where outbound effort is going or where leads are stalling.",
        "customerValue": "Evidence-based coaching and lead coverage instead of reactive check-ins.",
        "whatChanged": "Building the BDR activity and lead redistribution console.",
        "availability": "Coming Soon",
        "bestFor": ["Sales Managers"],
        "tags": ["sales", "activity", "roadmap"],
        "epic_match": ["bdr activity", "lead redistribution"],
    },

    # ──────────────────── Continuous Improvement Loop ─────────────────────
    {
        "id": "loop-knowledge-gap-detection",
        "track": "support",
        "module": "Continuous Improvement Loop",
        "featureName": "Knowledge Gap Detection & Enrichment",
        "shortDescription": "Detects where answers are weak or missing and turns those gaps into drafted knowledge updates for human review.",
        "customerProblem": "Most operations only improve during manual reviews or after problems become visible.",
        "customerValue": "Knowledge gaps become reviewed improvements, so the system gets better with use.",
        "whatChanged": "Building QA-driven knowledge gap detection and article enrichment.",
        "availability": "Coming Soon",
        "bestFor": ["Support Leaders", "Supervisors"],
        "tags": ["loop", "self-improving", "roadmap"],
        "epic_match": ["knowledge gap detection", "article enrichment", "enrichment trigger"],
    },
    {
        "id": "loop-sales-outcome-feedback",
        "track": "sales",
        "module": "Continuous Improvement Loop",
        "featureName": "Won/Lost Pattern Feedback",
        "shortDescription": "Feeds objection patterns and won/lost outcomes back into playbooks and outreach guidance.",
        "customerProblem": "Sales learning lives in people's heads and rarely improves the next campaign systematically.",
        "customerValue": "Win/loss patterns continuously sharpen future playbooks and outreach.",
        "whatChanged": "Planned sales improvement loop linking outcomes back to playbooks.",
        "availability": "Coming Soon",
        "bestFor": ["Sales Leaders", "Sales Managers"],
        "tags": ["loop", "sales", "roadmap"],
        "epic_match": ["won/lost", "objection analysis", "playbook auto-refiner", "objection handling"],
    },

    # ────────────────────── Platform / Integrations ───────────────────────
    {
        "id": "platform-zendesk-sync",
        "track": "support",
        "module": "Platform / Integrations",
        "featureName": "Zendesk Integration",
        "shortDescription": "Two-way connection with Zendesk so AiMY works inside your existing helpdesk.",
        "customerProblem": "Bolt-on tools that don't sync with the helpdesk create double work and stale data.",
        "customerValue": "AiMY fits into the tools your team already uses, with no rip-and-replace.",
        "whatChanged": "Released Zendesk sync.",
        "availability": "Released",
        "bestFor": ["Support Leaders"],
        "tags": ["integrations", "zendesk"],
        "epic_match": ["zendesk sync"],
    },
    {
        "id": "platform-helpdesk-integrations",
        "track": "support",
        "module": "Platform / Integrations",
        "featureName": "Helpdesk Integrations",
        "shortDescription": "Connects AiMY to your existing support stack so interactions flow in automatically.",
        "customerProblem": "Manual exports and disconnected systems slow onboarding and leave gaps in coverage.",
        "customerValue": "Plug-and-play setup that connects your existing ticketing to AiMY.",
        "whatChanged": "Building Zendesk and Freshdesk integrations.",
        "availability": "Coming Soon",
        "bestFor": ["Support Leaders"],
        "tags": ["integrations", "roadmap"],
        "epic_match": ["integration zendesk", "integration freshdesk"],
    },
]
